variable_from_inventories: "Hello from inventories"
aws_region: "eu-central"


#vars
cfn_stack_name_for_microservice1: "microservice1-{{ account }}-stack"
cfn_stack_name_for_microservice2: "microservice2-{{ account }}-stack"
region: "eu-central-1"
account: "lab-eu-central"
instance_type: "t2.micro"
image_id: "ami-0a485299eeb98b979"
application: "deploy-demo"
full_stack: "Yes"
artifactory_host: "demofordeploy.jfrog.io"
ecs_tasks_count: 1

ecs_artifactory_credentials: "arn:aws:secretsmanager:eu-central-1:544176100230:secret:deployfordemo-Artifactory-Credential-xshSuW"
ecs_subnets: "subnet-07ce1bae678b5a9cb,subnet-02345fc06e28d3f2d,subnet-0c771ead1d7ecaff3"
ecs_security_group: "Value is created and taken from CFN - microservice1EcsSecurityGroup"
ecs_execution_role: "Value is created and taken from CFN - microservice1EcsRole"
alb_subnets: "subnet-07ce1bae678b5a9cb,subnet-0c771ead1d7ecaff3"
alb_security_group: "Value is created and taken from CFN - microservice1AlbSg"
alb_listener_certificate_for_microservice1: "arn:aws:acm:eu-central-1:544176100230:certificate/baafc45e-7222-42a0-84b5-6092541ec6c6"
alb_listener_certificate_for_microservice2: "arn:aws:acm:eu-central-1:544176100230:certificate/03119e0b-f842-45aa-a263-6eef204db376"
vpc_id: "vpc-026bc198ec4d1e1cb"

kms_secret_holder_arn: "arn:aws:secretsmanager:eu-central-1:544176100230:secret:deploydemo/lab/kms-key-arn-yLlLyH"