---
- name: Generate CFN Template File
  template:
    src: "{{role_path}}/templates/medusa.cf.j2.yml"
    dest: "{{role_path}}/files/medusa.cf.j2.yml"


- name: Create Medusa Stack
  cloudformation:
    stack_name: "{{ cfn_stack_name }}"
    state: "present"
    region: "{{ region }}"
    template: "{{role_path}}/files/medusa.cf.j2.yml"
    template_parameters:
      Account: "{{ account }}"
      FullStack: "{{ full_stack }}"
      VersionTag: "{{ version_tag }}"
      ArtifactoryHost: "{{ artifactory_host }}"
      AlbUserPoolArn: "{{ cognito_user_pool_arn }}"
      AlbUserPoolClientId: "{{ cognito_user_pool_client_id }}"
      AlbUserPoolDomain: "{{ cognito_user_pool_domain }}"
      EcsServiceDesiredTaskCount: "{{ ecs_tasks_count }}"
      EcsEnvVars: "{{ ecs_vars_json_data | to_json }}"
      EcsArtifactoryCredentials: "{{ ecs_artifactory_credentials }}"
      EcsSubnets: "{{ ecs_subnets }}"
      EcsSecurityGroup: "{{ ecs_security_group }}"
      EcsExecutionRole: "{{ ecs_execution_role }}"
      AlbSubnets: "{{ alb_subnets }}"
      AlbSecurityGroup: "{{ alb_security_group }}"
      AlbListenerCertificate: "{{ alb_listener_certificate }}"
      VpcId: "{{ vpc_id }}"
    tags:
      Application: "{{ application }}"
