---
- name: Generate CFN Template File
  template:
    src: "{{role_path}}/templates/medusa.cf.j2.yml"
    dest: "{{role_path}}/files/medusa.cf.j2.yml"


- name: Create Medusa Stack
  cloudformation:
    stack_name: "{{ cfn_stack_name }}"
    state: "present"
    region: "{{ region }}"
    template: "{{role_path}}/files/medusa.cf.j2.yml"
    template_parameters:
      InstanceType: "{{ instance_type }}"
      ImageId: "{{ image_id }}"
    tags:
      Application: "deploydemo"
