---
- name: trigger code deploy pipeline
  hosts: deploydemo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: true
  connection: local
  environment:
    AWS_REGION: "{{ aws_region }}"
  roles:
    - app-config