---
- name: trigger code deploy pipeline
  hosts: deploydemo
  gather_facts: true
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  environment:
    AWS_REGION: "{{ aws_region }}"
  roles:
    - role1
    - app-config